[env:esp32dev]

platform = espressif32

board = esp32dev

framework = arduino

monitor_speed = 115200

upload_speed = 921600

monitor_filters = time

lib_deps =
    mcci-catena/MCCI LoRaWAN LMIC library

build_flags =
    -D CFG_eu868=1
    -D CFG_sx1276_radio=1
    -D ARDUINO_LMIC_PROJECT_CONFIG_H_SUPPRESS

lib_ldf_mode = deep+