[env:esp32dev]

platform = espressif32

board = esp32dev

framework = arduino

monitor_speed = 115200

lib_deps =

    mcci-catena/MCCI LoRaWAN LMIC library

    adafruit/Adafruit BME280 Library

    adafruit/Adafruit SHT31 Library

    adafruit/Adafruit Unified Sensor

build_flags =

    -D CFG_eu868=1

    -D CFG_sx1276_radio=1

    -D ARDUINO_LMIC_PROJECT_CONFIG_H_SUPPRESS